### ISSUE TITLE
Final Testing to Release

### ISSUE THREAD

**Issue by Puskin2911** [Puskin2911/Chinese-Chess-Game-Online#82]
- Hi, All. So everything is done already. Although we have tested through each stage of the project while following the Agile model, I also want all of us to do the final test before release.
- I have also deployed the application to AWS. You can test right here [Chinese Chess game online](http://ec2-54-169-208-186.ap-southeast-1.compute.amazonaws.com)

**Comment by Hokage-Itachi** [comment]
Go, play some games....

**Comment by Hokage-Itachi** [comment]
when the general was checked, the UI display not pretty...

**Comment by dang007x** [comment]
Woo hoo, nice bro @Puskin2911 . @Hokage-Itachi  Can you do better?

**Comment by Hokage-Itachi** [comment]
Just feedback... I really not good at UI design...

**Comment by thanhcute123** [comment]
Có một vài vấn đề đã xảy ra:
- Mình lại có thể tự đấu với mình

**Comment by Puskin2911** [comment]
@thanhcute123  It seem my fault. Can you update to fix this bug @dang007x

**Comment by dang007x** [comment]
OK, Done.

**Comment by Puskin2911** [comment]
Something else  If everything is good. I will create release version

**Comment by bichphuonggb** [comment]
Tôi thấy giao diện người dùng khá đẹp, mọi thứ khi thử nghiệm đều ổn. Great!!! @Puskin2911
